version: '3.3'

services:
  db:
    image: influxdb:1.8.3

    environment:
        INFLUXDB_ADMIN_PASSWORD: Start2020
        INFLUXDB_USER: fhem
        INFLUXDB_USER_PASSWORD: fhem
    ports:
      - 8086:8086
    networks:
      - net
    deploy:               
      resources:          
        reservations:     
          cpus: '0.25'
          memory: 64M    
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/influxdb
  web:
    image: fabian1233/fhem-influxdb:latest
    environment:
        FHEM_BACKUP: "true"
        FHEM_AUTOSAVE: 1
        ENABLE_TELNET: "true"
    networks:
      - net
    ports:
      - 8183:8083
#      - 1883:1883
    deploy:           
      resources:      
        reservations: 
          cpus: '0.25'
          memory: 128M
    volumes:
      - type: volume
        source: fhem-log
        target: /opt/fhem/log
        volume:
          nocopy: true
      - type: volume
        source: fhem-conf
        target: /opt/fhem/conf
        volume:
          nocopy: true
      - type: volume          
        source: fhem-data     
        target: /opt/fhem/FHEM
        volume:               
          nocopy: true        
      - type: volume
        source: fhem-backup
        target: /backup
        volume:
          nocopy: true
      - type: volume       
        source: fhem-www
        target: /opt/fhem/www    
        volume:            
          nocopy: true     
networks:
  net:
    driver: overlay
    attachable: true

volumes:
  db-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /nfsdata/volumes/fhem_test/influxdb
  fhem-data:
    driver: local                       
    driver_opts:                        
      o: bind                           
      type: none                        
      device: /nfsdata/volumes/fhem_test/data
  fhem-conf:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /nfsdata/volumes/fhem_test/conf
  fhem-log:                     
    driver: local
    driver_opts:                
      o: bind                    
      type: none                 
      device: /nfsdata/volumes/fhem_test/log 
  fhem-backup:                    
    driver: local              
    driver_opts:               
      o: bind                  
      type: none               
      device: /nfsdata/volumes/fhem_test/backup
  fhem-www:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /nfsdata/volumes/fhem_test/www
