version: '3.3'

services:
  db:
    image: beercan1989/arm-mysql
    environment:
        MYSQL_ROOT_USER: root
#        MYSQL_ROOT_PASSWORD: Start2020
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
        MYSQL_DATABASE: fhem
        MYSQL_USER: fhem
        MYSQL_PASSWORD: fhem
    deploy:               
      resources:          
        reservations:     
          cpus: '0.25'
          memory: 64M    
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/mysql
  web:
    image: fabian1233/fhem-web
    environment:
        FHEM_BACKUP: "true"
        FHEM_AUTOSAVE: 1
        ENABLE_TELNET: "true"
    ports:
      - 8083:8083
      - 1883:1883
    labels:                                                        
      - "traefik.enable=true"                                      
      - "traefik.http.routers.fhem.rule=Host(`fhem.fschneider.at`)"
      - "traefik.http.routers.fhem.entrypoints=web"                
      - "traefik.http.routers.fhem.port=8083"                      
    deploy:           
      resources:      
        reservations: 
          cpus: '0.25'
          memory: 128M
    volumes:
      - type: volume
        source: fhem-log
        target: /opt/fhem/log
        volume:
          nocopy: true
      - type: volume
        source: fhem-conf
        target: /opt/fhem/conf
        volume:
          nocopy: true
      - type: volume          
        source: fhem-data     
        target: /opt/fhem/FHEM
        volume:               
          nocopy: true        
      - type: volume
        source: fhem-backup
        target: /backup
        volume:
          nocopy: true
      - type: volume       
        source: fhem-www
        target: /opt/fhem/www    
        volume:            
          nocopy: true     
#networks:
#  net:
#    driver: overlay
#    attachable: true

volumes:
  db-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /nfsdata/fhem/mysql
  fhem-data:
    driver: local                       
    driver_opts:                        
      o: bind                           
      type: none                        
      device: /nfsdata/fhem/data
  fhem-conf:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /nfsdata/fhem/conf
  fhem-log:                     
    driver: local
    driver_opts:                
      o: bind                    
      type: none                 
      device: /nfsdata/fhem/log 
  fhem-backup:                    
    driver: local              
    driver_opts:               
      o: bind                  
      type: none               
      device: /nfsdata/fhem/backup
  fhem-www:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /nfsdata/fhem/www
